# Generated by Django 3.1.2 on 2020-12-31 21:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_delete_place_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_file', models.FileField(upload_to='music')),
                ('added_time', models.DateTimeField(default=datetime.datetime(2020, 12, 31, 13, 49, 33, 918051))),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
