# Generated by Django 3.1.2 on 2021-01-19 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 12, 29, 11, 693696)),
        ),
    ]
