# Generated by Django 3.1.2 on 2021-01-20 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210119_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 19, 47, 40, 807614)),
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 19, 19, 47, 40, 808615))),
                ('songs', models.ManyToManyField(blank=True, null=True, to='application.song')),
            ],
        ),
    ]
