# Generated by Django 3.1.2 on 2021-01-20 03:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0008_auto_20210119_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 19, 51, 19, 960685)),
        ),
        migrations.AlterField(
            model_name='song',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 19, 51, 19, 959686)),
        ),
    ]
