# Generated by Django 3.1.2 on 2021-01-21 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210119_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='prompts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='prompts')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2021, 1, 21, 10, 36, 10, 925310))),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 10, 36, 10, 925310)),
        ),
        migrations.AlterField(
            model_name='song',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 10, 36, 10, 925310)),
        ),
    ]
