# Generated by Django 3.1.2 on 2021-01-21 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210121_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 15, 43, 52, 244762)),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 15, 43, 52, 243761)),
        ),
        migrations.AlterField(
            model_name='song',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 15, 43, 52, 243761)),
        ),
    ]
