# Generated by Django 3.1.2 on 2021-01-21 23:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210121_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompts',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 15, 54, 10, 187494)),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 15, 54, 10, 185475)),
        ),
        migrations.AlterField(
            model_name='song',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 15, 54, 10, 186493)),
        ),
        migrations.CreateModel(
            name='prompts_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.IntegerField()),
                ('which_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.prompts')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='all_prompts',
            field=models.ManyToManyField(blank=True, null=True, to='application.prompts_time'),
        ),
    ]
