# Generated by Django 3.1.2 on 2021-01-22 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20210121_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 16, 5, 4, 988069)),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 16, 5, 4, 986067)),
        ),
        migrations.AlterField(
            model_name='song',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 16, 5, 4, 987068)),
        ),
    ]
